---
title: "Building replicate models"
author: "Dan Warren"
date: "8/12/2020"
output:
  pdf_document: default
  html_document: default
---


```{r}
library(ENMTools)

monticola <- iberolacerta.clade$species$monticola

```

Here's a quick and dirty way to do a bunch of replicate models where we repeat the random sampling of our training and test data.

```{r message = FALSE, warning = FALSE}
reps <- list()

for(i in 1:10){
  thisname <- paste0("rep", i)
  reps[[thisname]] <- enmtools.gam(monticola, euro.worldclim, test.prop = 0.3)
}

repstack <- reps[[1]]$suitability

for(i in 2:10){
  repstack <- addLayer(repstack, reps[[i]]$suitability)
}

names(repstack) <- names(reps)

meanreps <- raster::calc(repstack, fun = mean, na.rm = T)
plot(meanreps)

sdreps <- raster::calc(repstack, fun = sd, na.rm = T)
plot(sdreps)
```


Or perhaps you want to do a bootstrap instead?  That's a bit more work, but still not too bad; all we need to do is add some code to resample our presence data with replacement before the train/test split.

```{r message = FALSE, warning = FALSE}
reps <- list()

for(i in 1:10){
  thisrep <- monticola
  npres <- nrow(thisrep$presence.points)
  bootrows <- sample(1:npres, npres, replace = TRUE)
  thisrep$presence.points <- thisrep$presence.points[bootrows,]
  thisname <- paste0("rep", i)
  reps[[thisname]] <- enmtools.gam(thisrep, euro.worldclim, test.prop = 0.3)
}

bootstack <- reps[[1]]$suitability

for(i in 2:10){
  bootstack <- addLayer(bootstack, reps[[i]]$suitability)
}

names(bootstack) <- names(reps)

meanboot <- calc(bootstack, fun = mean, na.rm = T)
plot(meanboot)

sdboot <- raster::calc(bootstack, fun = sd, na.rm = T)
plot(sdboot)






```

